controller_list:
  - name: fake_hand_ee_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_7
      - joint_8
  - name: fake_robot_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
initial:  # Define initial robot poses per group
  - group: hand_ee
    pose: hand_close
  - group: robot_arm
    pose: pose_1